[theme]
base="light"
primaryColor="#034424"
backgroundColor="#2b9e65"
secondaryBackgroundColor="#87d0ab"
textColor="#FEFFFF"
font="sans serif"

# Max size, in megabytes, of messages that can be sent via the WebSocket
# connection.
# Default: 200
maxMessageSize = 400